### ISSUE TITLE
problema no projeto-android

### ISSUE THREAD

**Issue by yagoFerro** [cursoemvideo/cursoemvideo-html5#31]
botei o rpeojeto no ar e quando vou ver pelo computador,
a fonte android nao aparece no projeto,mas se eu procurar o mesmo
pelo celular  a fonte aparece normalmente

**Comment by murilomcabral** [comment]
Não dizer ainda o porque, mas veja que a pasta **"fontes"** não aparece na lista de arquivos da página.
- Certifique-se de estar na página do projeto
- Pressione a tecla "F12" **ou** clique com o botão direito do mouse na página e selecione a opção "Inspecionar";
![image](https://github.com/cursoemvideo/cursoemvideo-html5/assets/95389598/b1992c5c-9f72-4fb1-a8fa-713bbfe5d05e)
- Selecione a aba "Fontes"/"Origin" **ou** use o atalho Ctrl+Shift+P e cole esse comando, sem as aspas ">Mostrar a guia "Página" e pressione "Enter" no teclado.
-  Aqui você verifica os arquivos que fazem a página.
![image](https://github.com/cursoemvideo/cursoemvideo-html5/assets/95389598/a0e8c29d-f849-442a-b962-5b58c6a99c58)

---
*A pasta aparece no repositório normalmente.*

![image](https://github.com/cursoemvideo/cursoemvideo-html5/assets/95389598/94f7b84d-9f5b-4646-961a-8dbd45618c32)

---
*Porém na página isso não acontece como deveria.*

![image](https://github.com/cursoemvideo/cursoemvideo-html5/assets/95389598/cd1bfe52-30e9-4a1b-9f73-474af742dd2a)
---
Vi que pasta existe no repositório, mas na página não aparece.

Minha sugestão seria, **retire a página do ar, e depois refazer o deploy no *github-pages*. Imagino que seja um bug ou algo do tipo. Caso eu descubra algo mais eu retorno aqui sobre o seu problema**.

**Comment by yagoFerro** [comment]
Olá muito obrigado pela dica,vou tenta
